name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # packager wants full history to derive version info

      - name: Package and upload
        uses: BigWigsMods/packager@v2.5.1

        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
